In this chapter, you'll learn how to import data into Python from all types of flat files, a simple and prevalent form of data storage. You've previously learned how to use NumPy and pandas - you will learn how to use these packages to import flat files, as well as how to customize your imports.

### reading a Text file

In [1]:
filename = 'huck_finn.txt'
file = open(filename, mode='r')  # r is to read
text = file.read()
file.close()

In [2]:
print(text)

YOU don't know about me without you have read a book by the
name of The Adventures of Tom Sawyer; but that ain't no
matter. That book was made by Mr. Mark Twain, and he told
the truth, mainly. There was things which he stretched, but
mainly he told the truth. That is nothing. never seen
anybody but lied one time or another, without it was Aunt
Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt
Polly, she is--and Mary, and the Widow Douglas is all told
about in that book, which is mostly a true book, with some
stretchers, as I said before.




### Writting to a file

```python
filename = 'huck_finn.txt'
file = open(filename, mode='w')  # w is to write
file.close()
```

### Context maneger `with`

In [3]:
with open('huck_finn.txt', 'r') as file:
    print(file.read())

YOU don't know about me without you have read a book by the
name of The Adventures of Tom Sawyer; but that ain't no
matter. That book was made by Mr. Mark Twain, and he told
the truth, mainly. There was things which he stretched, but
mainly he told the truth. That is nothing. never seen
anybody but lied one time or another, without it was Aunt
Polly, or the widow, or maybe Mary. Aunt Polly--Tom's Aunt
Polly, she is--and Mary, and the Widow Douglas is all told
about in that book, which is mostly a true book, with some
stretchers, as I said before.




---
# Lets Practice!

```python
# Open a file: file
file = open('moby_dick.txt','r')

# Print it
print(file.read())

# Check whether file is closed
print(file.closed)

# Close file
file.close()

# Check whether file is closed
print(file.closed)

```
```python
# Read & print the first 3 lines
with open('moby_dick.txt') as file:
    print(file.readline())
    print(file.readline())
    print(file.readline())

```


#  The importance of flat file s in datascience

In [4]:
import pandas as pd
titanic = pd.read_csv('titanic_sub.csv')
titanic.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [5]:
with open('titanic_sub.csv', 'r') as file:
    print(file.read())

PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,male,22.0,1,0,A/5 21171,7.25,,S
2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,female,26.0,0,0,STON/O2. 3101282,7.925,,S
4,1,1,female,35.0,1,0,113803,53.1,C123,S
5,0,3,male,35.0,0,0,373450,8.05,,S
6,0,3,male,,0,0,330877,8.4583,,Q
7,0,1,male,54.0,0,0,17463,51.8625,E46,S
8,0,3,male,2.0,3,1,349909,21.075,,S
9,1,3,female,27.0,0,2,347742,11.1333,,S
10,1,2,female,14.0,1,0,237736,30.0708,,C
11,1,3,female,4.0,1,1,PP 9549,16.7,G6,S
12,1,1,female,58.0,0,0,113783,26.55,C103,S
13,0,3,male,20.0,0,0,A/5. 2151,8.05,,S
14,0,3,male,39.0,1,5,347082,31.275,,S
15,0,3,female,14.0,0,0,350406,7.8542,,S
16,1,2,female,55.0,0,0,248706,16.0,,S
17,0,3,male,2.0,4,1,382652,29.125,,Q
18,1,2,male,,0,0,244373,13.0,,S
19,0,3,female,31.0,1,0,345763,18.0,,S
20,1,3,female,,0,0,2649,7.225,,C
21,0,2,male,35.0,0,0,239865,26.0,,S
22,1,2,male,34.0,0,0,248698,13.0,D56,S
23,1,3,female,15.0,0,0,330923,8.0292,,Q
24,1,1,male,28.0,0,0,113788,35.5,A6

## Flat files
- Text files containgi records
- tat is, table data
- column : feature or attrubute

```csv
PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,male,22.0,1,0,A/5 21171,7.25,,S
2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,female,26.0,0,0,STON/O2. 3101282,7.925,,S
```

## Header
```csv
PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
...
```

## File extension
-`.csv` Comma separated values
- `.txt` : text file
- commas, tabs : delimeters

## Tab-delimited file

In [6]:
cat seaslug.txt

Time	Percent
99	0.067
99	0.133
99	0.067
99	0
99	0
0	0.5
0	0.467
0	0.857
0	0.5
0	0.357
0	0.533
5	0.467
5	0.467
5	0.125
5	0.4
5	0.214
5	0.4
10	0.067
10	0.067
10	0.333
10	0.333
10	0.133
10	0.133
15	0.267
15	0.286
15	0.333
15	0.214
15	0
15	0
20	0.267
20	0.2
20	0.267
20	0.437
20	0.077
20	0.067
25	0.133
25	0.267
25	0.412
25	0
25	0.067
25	0.133
30	0
30	0.071
30	0
30	0.067
30	0.067
30	0.133

---
# Let's Practice!

# Importing flat files using Numpy

## Why numpy?
- numpy arrasy: standar for storing numerical data
- essentila for otehr pakages: ex sckilit-learn

- loadtxt()
- genfromtxt()

In [7]:
import numpy as np
filename = 'mnist_kaggle_some_rows.csv'
data = np.loadtxt(filename, delimiter=',')
data

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

## Customizing your numpy import

In [8]:
import numpy as np
filename = 'mnist_kaggle_some_rows.csv'
data = np.loadtxt(filename, delimiter=',', skiprows=1)
data

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [9]:
import numpy as np
filename = 'mnist_kaggle_some_rows.csv'
data = np.loadtxt(filename, delimiter=',', skiprows=1, usecols=[0,2])
data

array([[0., 0.],
       [1., 0.],
       [4., 0.],
       [0., 0.],
       [0., 0.],
       [7., 0.],
       [3., 0.],
       [5., 0.],
       [3., 0.],
       [8., 0.],
       [9., 0.],
       [1., 0.],
       [3., 0.],
       [3., 0.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [7., 0.],
       [5., 0.],
       [8., 0.],
       [6., 0.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [3., 0.],
       [6., 0.],
       [9., 0.],
       [9., 0.],
       [7., 0.],
       [8., 0.],
       [9., 0.],
       [4., 0.],
       [9., 0.],
       [2., 0.],
       [1., 0.],
       [3., 0.],
       [1., 0.],
       [1., 0.],
       [4., 0.],
       [9., 0.],
       [1., 0.],
       [4., 0.],
       [4., 0.],
       [2., 0.],
       [6., 0.],
       [3., 0.],
       [7., 0.],
       [7., 0.],
       [4., 0.],
       [7., 0.],
       [5., 0.],
       [1., 0.],
       [9., 0.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [3., 0.],
       [9., 0.],
       [1., 0.

---
# Lets practice!

# Importing flat files using pandas

## What a data scientis needs
- two-dimentional labeled data structures
- columns of potentially different types
- manipulate, slice, reshape, grouby, join, merge
- perform statistics
- work with time series data

## Manipulating pandas DataFrames
-  Exploratory data analysis
- Data wrangling
- Data preprocessing
- Building models
- Visualization
- Standard and best practice to use pandas

## Importing using pandas

In [10]:
import pandas as pd
filename = 'titanic_sub.csv'

data = pd.read_csv(filename)
data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

---
# Lets practice

```python
# Import package
import numpy as np

# Assign filename to variable: file
file = 'digits.csv'

# Load file as array: digits
digits = np.loadtxt(file, delimiter=',')

# Print datatype of digits
print(type(digits))

# Select and reshape a row
im = digits[21, 1:]
im_sq = np.reshape(im, (28, 28))

# Plot reshaped data (matplotlib.pyplot already loaded as plt)
plt.imshow(im_sq, cmap='Greys', interpolation='nearest')
plt.show()
```

```python
# Import numpy
import numpy as np

# Assign the filename: file
file = 'digits_header.txt'

# Load the data: data
data = np.loadtxt(file, delimiter='\t', skiprows=1, usecols=[0,2])

# Print data
print(data)
```

```python
# Assign filename: file
file = 'seaslug.txt'

# Import file: data
data = np.loadtxt(file, delimiter='\t', dtype=str)

# Print the first element of data
print(data[0])

# Import data as floats and skip the first row: data_float
data_float = np.loadtxt(file, delimiter='\t', dtype=float, skiprows=1)

# Print the 10th element of data_float
print(data_float[9])

# Plot a scatterplot of the data
plt.scatter(data_float[:, 0], data_float[:, 1])
plt.xlabel('time (min.)')
plt.ylabel('percentage of larvae')
plt.show()
```

In [11]:
import numpy as np
# Assign the filename: file
file = 'titanic_sub.csv'

# Import file using np.recfromcsv: d
d = np.recfromcsv(file)

# Print out first three entries of d
print(d[:3])


[(1, 0, 3, b'male', 22., 1, 0, b'A/5 21171',  7.25  , b'', b'S')
 (2, 1, 1, b'female', 38., 1, 0, b'PC 17599', 71.2833, b'C85', b'C')
 (3, 1, 3, b'female', 26., 0, 0, b'STON/O2. 3101282',  7.925 , b'', b'S')]


/Users/franciscosalas/miniconda3/envs/datacamp/lib/python3.6/site-packages/numpy/lib/npyio.py:2258: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)


In [12]:
# Import pandas as pd
import pandas as pd

# Assign the filename: file
file = 'titanic_sub.csv'

# Read the file into a DataFrame: df
df = pd.read_csv(file)

# View the head of the DataFrame
print(df.head())


   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  


```python
# Assign the filename: file
file = 'digits.csv'

# Read the first 5 rows of the file into a DataFrame: data
data = pd.read_csv(file,nrows=5, header=None)

# Build a numpy array from the DataFrame: data_array
data_array = np.array(data.values)

# Print the datatype of data_array to the shell
print(type(data_array))
```

```python
# Import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

# Assign filename: file
file = 'titanic_corrupt.txt'

# Import file: data
data = pd.read_csv(file, sep='\t', comment='#', na_values='Nothing')

# Print the head of the DataFrame
print(data.head())

# Plot 'Age' variable in a histogram
pd.DataFrame.hist(data[['Age']])
plt.xlabel('Age (years)')
plt.ylabel('count')
plt.show()
```